name: CI

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - dev
      - stable
  pull_request:
    branches:
      - dev
      - stable

jobs:
  lint:
    uses: metacraft-labs/devops-modules/.github/workflows/reusable-lint.yml@dev
    secrets:
      NIX_GITHUB_TOKEN: ${{ secrets.NIX_GITHUB_TOKEN }}
  ci:
    uses: metacraft-labs/devops-modules/.github/workflows/reusable-flake-checks-ci-matrix.yml@dev
    with:
      runners: | # json
        {
          "x86_64-linux": [
            "self-hosted", "linux", "x64"
          ],
          "aarch64-darwin": [
            "self-hosted", "macos", "arm64"
          ]
        }
